### ISSUE TITLE
    with open(file_path, "rb") as f: FileNotFoundError: [Errno 2] No such file or directory: 'results/gradio_temp.mp4'

### ISSUE THREAD

**Issue by invade-art** [invictus717/InteractiveVideo#3]
how to solve

**Comment by invictus717** [comment]
Could you please describe more details?

**Comment by invade-art** [comment]
After selecting an image to upload, this problem occurs when using Generate Video

**Comment by invade-art** [comment]
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/blocks.py", line 1332, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/blocks.py", line 460, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/root/autodl-tmp/conda/envs/stable/lib/python3.10/site-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/gradio_temp.mp4'
![Uploading 微信截图_20240228161321.png…]()

**Comment by invictus717** [comment]
Ok. It seems you are running a gradio demo, the error is due to you did not make the directory `results`. You can just run `mkdir results`

**Comment by invictus717** [comment]
If there is any problem, please feel free to reach out.

**Comment by invade-art** [comment]
ok, it work! but the video canvas is black and the video cannot be played T.T

**Comment by invade-art** [comment]
![微信截图_20240228162305](https://github.com/invictus717/InteractiveVideo/assets/84616698/4ecea9ae-7f72-4136-896d-cc3cc6ac4c21)

**Comment by invictus717** [comment]
> ok, it work! but the video canvas is black and the video cannot be played T.T

I did not meet this problem. You can double-check some details in your PC.

**Comment by invictus717** [comment]
> ![微信截图_20240228162305](https://private-user-images.githubusercontent.com/84616698/308473877-4ecea9ae-7f72-4136-896d-cc3cc6ac4c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDkxNDcsIm5iZiI6MTcwOTEwODg0NywicGF0aCI6Ii84NDYxNjY5OC8zMDg0NzM4NzctNGVjZWE5YWUtN2Y3Mi00MTM2LTg5NmQtY2MzY2M2YWM0YzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjNiMWRjMGJkZmQ3ZDRlZDkzZThmYTJhZWFkM2FmYTgxY2VjN2VlOWNhMjdjMzZmOTljNTdjOWMxNWQxZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXWxYKsOq2ox10MkpYvBLa-g8rsXpASh6DKjvxKoazg)

Good image and interesting attempt, enjoy yourself. BTW, it would be a better experience to run your local demo.
https://github.com/invictus717/InteractiveVideo#1-local-demo

**Comment by invade-art** [comment]
I downloaded it to play locally.thank!
